InternshipRegistrationSystem/Controllers/FormController.cs
using Entities.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Repositories;
using Repositories.Contract;
using Services.Contract;

namespace InternshipRegistrationSystem.Controllers
{
    public class FormController : Controller
    {
        private readonly RepositoryContext _context;
        private readonly IServiceManager _serviceManager;
        private readonly UserManager<User> _userManager;

        public FormController(RepositoryContext context, IServiceManager serviceManager, UserManager<User> userManager)
        {
            _context = context;
            _serviceManager = serviceManager;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult RegistrationForm()
        {
            var categoryList = _context.Category.ToList();
            var categorySelectList = categoryList.Select(c => new SelectListItem
            {
                Value = c.CategoryId.ToString(),
                Text = c.Name
            }).ToList();
            ViewBag.Category = categorySelectList;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Submit([FromForm] RegistrationForm registrationForm)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                registrationForm.CandidateId = user!.Id;
                _serviceManager.RegistrationFormService.CreateOne(registrationForm);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> RegistrationList()
        {
            try
            {
                var registrationList = _serviceManager.RegistrationFormService.GetAll(false);
                var registrationListQueryable = registrationList.AsQueryable().Include(r => r.Status);
                var currentUser = await _userManager.GetUserAsync(User);
                var userId = currentUser!.Id;
                var registrationListByCurrentCandidate = registrationListQueryable.Where(r => r.CandidateId.Equals(userId));
                var registrationListByCurrentCandidateList = registrationListByCurrentCandidate.ToList();
                return View(registrationListByCurrentCandidateList);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> ApplicationsPendingAssistantApproval()
        {
            try
            {
                var registrationList = _serviceManager.RegistrationFormService.GetAll(false);
                var registrationListQueryable = registrationList.AsQueryable().Include(r => r.Status);
                var currentUser = await _userManager.GetUserAsync(User);
                
                var categoryId = currentUser!.CategoryId;
                var registrationListByCurrentCandidate = registrationListQueryable.Where(r => r.CategoryId.Equals(categoryId) && r.StatusId.Equals(1));
                var registrationListByCurrentCandidateList = registrationListByCurrentCandidate.ToList();
                return View(registrationListByCurrentCandidateList);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> ApplicationsPendingAdministratorApproval()
        {
            try
            {
                var registrationList = _serviceManager.RegistrationFormService.GetAll(false);
                var registrationListQueryable = registrationList.AsQueryable().Include(r => r.Status);
                var currentUser = await _userManager.GetUserAsync(User);

                var professorId = currentUser!.Id;
                var registrationListByCurrentCandidate = registrationListQueryable.Where(r => r.ProfessorId.Equals(professorId) && r.StatusId.Equals(3));
                var registrationListByCurrentCandidateList = registrationListByCurrentCandidate.ToList();
                return View(registrationListByCurrentCandidateList);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> ResearchApprove([FromRoute] int id)
        {
            try
            {
                var currentUser = await _userManager.GetUserAsync(User);
                var professorId = currentUser!.ProfessorId;
                var registrationModel = _serviceManager.RegistrationFormService.GetOne(id, true);
                registrationModel!.StatusId = 3;
                registrationModel!.ProfessorId = professorId;
                _serviceManager.RegistrationFormService.UpdateOne(registrationModel);
                return View("ApplicationsPendingAssistantApproval");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", ex.Message);
            }
        }
        [HttpGet]
        public IActionResult ResearchReject([FromRoute] int id)
        {
            try
            {
                var registrationModel = _serviceManager.RegistrationFormService.GetOne(id, true);
                registrationModel!.StatusId = 2;
                _serviceManager.RegistrationFormService.UpdateOne(registrationModel);
                return View("ApplicationsPendingAssistantApproval");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> AdministratorApprove([FromRoute] int id)
        {
            try
            {
                var currentUser = await _userManager.GetUserAsync(User);
                var professorId = currentUser!.ProfessorId;
                var registrationModel = _serviceManager.RegistrationFormService.GetOne(id, true);
                var applicantId = registrationModel!.CandidateId;
                var candidated = await _userManager.FindByIdAsync(applicantId.ToString()!);
                registrationModel!.StatusId = 4;
                await _userManager.AddToRoleAsync(candidated!, "Stajyer");
                _serviceManager.RegistrationFormService.UpdateOne(registrationModel);
                return View("ApplicationsPendingAdministratorApproval");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", ex.Message);
            }
        
        }
        [HttpGet]
        public IActionResult AdministratorReject([FromRoute] int id)
        {
            try
            {
                var registrationModel = _serviceManager.RegistrationFormService.GetOne(id, true);
                registrationModel!.StatusId = 2;
                _serviceManager.RegistrationFormService.UpdateOne(registrationModel);
                return View("ApplicationsPendingAdministratorApproval");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", ex.Message);
            }
        }
    }
}

InternshipRegistrationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternshipRegistrationSystem</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InternshipRegistrationSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="justify-content-end">
                <a href="/User/Login" style="margin-right: 1rem" class="btn btn-danger">Login</a>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - InternshipRegistrationSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        window.addEventListener('unload', function () {
            navigator.sendBeacon('/User/Logout');
        });
    </script>
</body>
</html>

InternshipRegistrationSystem/Views/Shared/_LayoutAssistant.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternshipRegistrationSystem</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InternshipRegistrationSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Form" asp-action="ApplicationsPendingAssistantApproval">Asistan Onayı Bekleyen Başvurular</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="d-flex justify-content-end" style="width: auto; margin-right: 1rem">
                <form method="post" asp-controller="User" asp-action="Logout">
                    <button type="submit" class="btn btn-danger">Çıkış</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - InternshipRegistrationSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        window.addEventListener('unload', function () {
            navigator.sendBeacon('/User/Logout');
        });
    </script>
</body>
</html>

InternshipRegistrationSystem/Views/Shared/_LayoutCandidateIntern.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternshipRegistrationSystem</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InternshipRegistrationSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Form" asp-action="RegistrationList">Başvurularım</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="d-flex justify-content-end" style="width: auto; margin-right: 1rem">
                <form method="post" asp-controller="User" asp-action="Logout">
                    <button type="submit" class="btn btn-danger">Çıkış</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - InternshipRegistrationSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        window.addEventListener('unload', function () {
            navigator.sendBeacon('https://localhost:7241/User/Logout');
        });
    </script>
</body>
</html>

InternshipRegistrationSystem/Views/Shared/_LayoutIntern.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternshipRegistrationSystem</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InternshipRegistrationSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="d-flex justify-content-end" style="width: auto; margin-right: 1rem">
                <form method="post" asp-controller="User" asp-action="Logout">
                    <button type="submit" class="btn btn-danger">Çıkış</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - InternshipRegistrationSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        window.addEventListener('unload', function () {
            navigator.sendBeacon('/User/Logout');
        });
    </script>
</body>
</html>

InternshipRegistrationSystem/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternshipRegistrationSystem</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InternshipRegistrationSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="margin-right: 1rem; float: right">
            <div class="btn-group">
                <a href="/User/CandidateSignUp" class="btn btn-success">Aday Kayıt</a>
                <a href="/User/ResearchAssistantSignUp" class="btn btn-outline-success">Araştırma Görevlisi Kayıt</a>
                <a href="/User/ProfessorSignUp" class="btn btn-success">Profesör Kayıt</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - InternshipRegistrationSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        window.addEventListener('unload', function () {
            navigator.sendBeacon('/User/Logout');
        });
    </script>
</body>
</html>

InternshipRegistrationSystem/Views/Shared/_LayoutProfessor.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternshipRegistrationSystem</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InternshipRegistrationSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Form" asp-action="ApplicationsPendingAdministratorApproval">Yönetici Onayı Bekleyen Başvurular</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="d-flex justify-content-end" style="width: auto; margin-right: 1rem">
                <form method="post" asp-controller="User" asp-action="Logout">
                    <button type="submit" class="btn btn-danger">Çıkış</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - InternshipRegistrationSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        window.addEventListener('unload', function () {
            navigator.sendBeacon('/User/Logout');
        });
    </script>
</body>
</html>